src/main/urls.py
from .views import *
from django.urls import path, include

app_name = "website"


urlpatterns = [
    path('', IndexPageView.as_view(), name='index'),
    path('services/', ServiceViewPage.as_view(), name='services'),
    path('about/', AboutViewPage.as_view(), name='about'),
    path('delivery/', DeliveryViewPage.as_view(), name='delivery'),
    path('payment', PaymentViewPage.as_view(), name='payment'),
    path('refund/', RefundViewPage.as_view(), name='refund'),
    path('contacts/', ContactViewPage.as_view(), name='contacts'),

    path('sfera-deyatelnosty/', ProcheeCategoryView.as_view(), name='sfera-deyatelnosty'),
    path('category/', CategoryViewPage.as_view(), name='category'),
    
    path('services/<slug:slug>/', ServicesDetailView.as_view(), name='services_detail'),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('<slug:slug>/products/', ProductListView.as_view(), name='product_list'),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),


    path('search/', search_products, name='search_products'),

]

src/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'main.views.custom_404'

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/templates/website/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %} О компании {% endblock %}



{% block content %}
<div class="container mt-1 mb-3">
  <div class="hero">
      <h1>О нашей компании</h1>
      <p>Мы создаем инновационные решения для вашего успеха</p>
  </div>
</div>

<style>
  
  .hero {
      background-image: url('{% static 'images/kz.webp' %}');
      color: white;
      padding: 60px 20px; /* Уменьшил отступы */
      text-align: center;
      border-radius: 15px;
  }

  .hero h1 {
      font-size: 2.5rem;
      font-weight: bold;
      color: white;
  }

  .hero p {
      font-size: 1.1rem;
  }

  .card {
      border: none;
      transition: transform 0.3s ease-in-out;
  }

  .card:hover {
      transform: translateY(-10px);
      box-shadow: 0 10px 20px rgba(0, 0, 0, 0.15);
  }

  /* Стили для мобильных устройств */
  @media (max-width: 768px) {
      .hero {
          padding: 40px 15px; /* Еще меньше отступов на мобильных */
      }
      .hero h1 {
          font-size: 2rem;
      }
      .hero p {
          font-size: 1rem;
      }
  }
</style>

<div class="container-xl mt-5 mb-5">
  <div class="row">
    <div class="col-12 mb-3">
      <h4 class="about-company-bottom__title" style="color: #262a31;"><a href="{% url 'website:about' %}">О компании</a></h4>
    </div>
    <div class="row">
      <div class="col-md-6 mb-2">
        <p class="fw-bold" style="color: black;">"Центр стального проката" – надежный поставщик строительных материалов в Казахстане.  </p>
        <p>Мы специализируемся на комплексных поставках металлопроката и сопутствующих материалов для строительства, промышленности и других сфер.</p>

        <p>Наши опытные менеджеры всегда готовы помочь с выбором продукции, подобрать оптимальное решение под ваши задачи и бюджет. Мы гарантируем качество материалов и своевременные поставки.  </p>
      </div>
      <div class="col-md-6">
        <ul class="list-unstyled">
          <p style="color: #032655;"><b>Наши преимущества:</b> </p>
          <li style="color: #032655;" class="mb-3">
              <span><b style="color: #032655; margin-right: 5px;">•</b></span> Прямые контракты с производителями – лучшие цены. Работаем без посредников, получая специальные условия от заводов. Это позволяет предлагать вам выгодные цены без переплат.
          </li>
          <li style="color: #032655;" class="mb-3">
              <span><b style="color: #032655; margin-right: 5px;">•</b></span> Собственные склады в Казахстане – стабильность поставок. Материалы всегда в наличии в нужном регионе. Быстрая отгрузка – минимизируем простои на вашем объекте.
          </li>
          <li style="color: #032655;" class="mb-3">
              <span><b style="color: #032655; margin-right: 5px;">•</b></span> Собственный автопарк – быстрая и надежная логистика. Доставляем точно в срок без задержек. Контролируем сохранность груза на всех этапах.
          </li>
          <li style="color: #032655;" class="mb-3">
              <span><b style="color: #032655; margin-right: 5px;">•</b></span> Опыт и гарантии. Более 10 лет успешной работы в тендерах и коммерческих поставках. Это значит:
              <ul>
                  <li style="color: #032655;">Мы выполняем обязательства в полном объеме.</li>
                  <li style="color: #032655;">Гарантируем качество материалов и соблюдение сроков.</li>
              </ul>
          </li>
      </ul>
      
      </div>
      <p style="color: black;" class="fw-bold mt-2">Почему с нами удобно работать? </p><br> <br>
      <p>
        Выгодные цены – за счет прямых договоров с заводами.
        
        Стабильность – собственные склады и логистика.
        
        Надежность – проверено годами сотрудничества с крупными заказчиками.
        
        Нужны качественные стройматериалы с доставкой? Оставьте заявку – подберем оптимальное решение для вашего проекта!</p>
    </div>
    
  </div>
</div>


<section class="mb-5">
  <div class="container">
    <div class="p-4 p-md-5" style="background-color: #0d1e4b; border-radius: 27px;">
      <div class="row align-items-center">
        <!-- Левая часть -->
        <div class="col-lg-7 text-white mb-4 mb-lg-0">
          <h2 class="fw-bold text-white">Получите бесплатную<br>консультацию от нашего<br>специалиста</h2>
        </div>

        <!-- Правая часть: Форма -->
        <div class="col-lg-5">
          <div class="bg-white p-4 rounded-4 shadow-sm">
            <h5 class="mb-3">Оставьте свои контакты и мы свяжемся с вами</h5>
        
          
            <!-- Bitrix24 форма -->
            <script data-b24-form="inline/57/rn8mlt" data-skip-moving="true">
(function(w,d,u){
var s=d.createElement('script');s.async=true;s.src=u+'?'+(Date.now()/180000|0);
var h=d.getElementsByTagName('script')[0];h.parentNode.insertBefore(s,h);
})(window,document,'https://cdn-ru.bitrix24.kz/b17734044/crm/form/loader_57.js');
</script>
          </div>
        </div>
        
        <style>
          .product-card {
            display: flex;
            align-items: center;
            gap: 12px;
            background-color: #fff;
            padding: 16px;
            border-radius: 16px;
            border: 1px solid #e7e7e9;
            margin-bottom: 20px;
          }
        
          .product-img {
            width: 60px;
            height: 60px;
            border-radius: 12px;
            object-fit: cover;
          }
        
          .product-title {
            font-weight: 600;
            font-size: 16px;
            color: #212529;
            margin: 0;
            text-decoration: none;
          }
        
          .product-meta {
            font-size: 14px;
            color: #6c757d;
            margin: 0;
          }
        
          .product-status {
            color: #198754;
            font-weight: 500;
          }
        
          .b24-form {
            overflow: hidden !important;
          }
        
          .b24-form-header-padding {
            display: none;
          }
        
          .b24-form-wrapper.b24-form-border-bottom {
            border-bottom: 0px;
          }

          .b24-form-padding-side {
            padding-left: 0px;
            padding-right: 0px;
            padding-top: 0px;
          }

          .b24-form-wrapper {
            min-height: 200px;
          }
        </style>

        
        
      </div>

      <!-- Контакты и менеджер -->
      
      <!-- Мобильная версия: фото, текст и иконки -->
      <div class="d-flex d-md-none align-items-center mt-4">
        <img src="{% static 'images/madina.jpeg' %}" alt="Менеджер Наталья" class="rounded-circle" width="60" height="60">
      
        <div class="ms-3">
          <small class="text-white-50">Ваш менеджер</small><br>
          <strong class="text-white">Мадина</strong>
        </div>
      
        <div class="d-flex gap-3 ms-auto">
          <!-- WhatsApp -->
          <a href="https://wa.me/77088009874" class="text-white text-decoration-none">
            <span class="d-inline-flex justify-content-center align-items-center rounded-circle bg-success" style="width: 40px; height: 40px;">
              <i class="bi bi-whatsapp text-white fs-5"></i>
            </span>
          </a>
      
          <!-- Телефон -->
          <a href="tel:+77088009874" class="text-white text-decoration-none">
            <span class="d-inline-flex justify-content-center align-items-center rounded-circle bg-success" style="width: 40px; height: 40px;">
              <i class="bi bi-telephone-fill text-white fs-5"></i>
            </span>
          </a>
        </div>
      </div>
      


      <!-- Десктопная версия: всё как раньше -->
      <div class="d-none d-md-flex flex-md-row justify-content-between align-items-center mt-4 gap-3">
        <div class="d-flex align-items-center">
          <img src="{% static 'images/madina.jpeg' %}" alt="Менеджер Наталья" class="rounded-circle me-3" width="60" height="60">
          <div>
            <small class="text-white-50">Ваш персональный менеджер</small><br>
            <strong class="text-white">Мадина</strong>
          </div>
        </div>

        <div class="d-flex flex-row gap-3 justify-content-end">
          <a href="https://wa.me/77088009874" class="text-white text-decoration-none d-flex align-items-center gap-2">
            <span class="d-inline-flex justify-content-center align-items-center rounded-circle bg-success" style="width: 36px; height: 36px;">
              <i class="bi bi-whatsapp text-white fs-5"></i>
            </span>
            +7 (708) 800 81 88
          </a>

          <a href="tel:+77088009874" class="text-white text-decoration-none d-flex align-items-center gap-2">
            <span class="d-inline-flex justify-content-center align-items-center rounded-circle bg-success" style="width: 36px; height: 36px;">
              <i class="bi bi-telephone-fill text-white fs-5"></i>
            </span>
            +7 (708) 800 81 88
          </a>
        </div>
      </div>


    </div>
  </div>
</section>


<style>
  .d-flex.flex-wrap.gap-4.justify-content-end {
    margin-right: 2%;
  }

  input[type="tel"] {
    border-left: 0;
  }
  
  .input-group-text {
    border-right: 0;
    border-color: #ced4da;
  }
  
</style>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
  

{% endblock %}

src/templates/website/contacts.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Контакты {% endblock %}


{% block content %}
<main>

    <!-- =======================
    Main banner START -->
    <section class="pt-4 pt-md-5">
        <div class="container">
            <div class="row mb-5">
                <div class="col-xl-10">
                    <!-- Title -->
                    <h1>Контакты</h1>
                    <p class="lead mb-0">💬 Наша команда готова помочь вам с любым вопросом. Оставьте заявку – и мы оперативно свяжемся с вами для решения вашей задачи.</p>
                </div>
            </div>
    
            <!-- Contact info -->
            <div class="row g-4">

                <!-- Contact item START -->
                <div class="col-md-6 col-xl-4">
                    <div class="card card-body shadow text-center align-items-center h-100">
                        <!-- Icon -->
                        <div class="icon-lg bg-info bg-opacity-10 text-info rounded-circle mb-2"><i class="bi bi-telephone fs-5"></i></div>
                        <!-- Title -->
                        <h5>Всегда на связи!</h5>
                        <p>Наши специалисты готовы помочь вам с выбором и ответить на любые вопросы.</p>
                        <!-- Buttons -->
                        <div class="d-grid gap-3 d-sm-block">
                            <button class="btn btn-sm" style="background-color: #032655; color: white;" onclick="callNumber('+77088009871')">
                                <i class="bi bi-phone me-2"></i>+7 (708) 800 98 71
                            </button>
                            
                            <button class="btn btn-sm btn-light" onclick="callNumber('+77088009872')">
                                <i class="bi bi-telephone me-2"></i>+7 (708) 800 98 72
                            </button>
                            
                            <script>
                                function callNumber(phoneNumber) {
                                    window.location.href = "tel:" + phoneNumber;
                                }
                            </script>
                            
                        </div>
                    </div>
                </div>
                <!-- Contact item END -->
            
                <!-- Contact item START -->
                <div class="col-md-6 col-xl-4 d-none d-md-block">
                    <div class="card card-body shadow text-center align-items-center h-100">
                        <!-- Icon -->
                        <div class="icon-lg bg-danger bg-opacity-10 text-danger rounded-circle mb-2"><i class="bi bi-envelope fs-5"></i></div>
                        <!-- Title -->
                        <h5>Корпоративная почта</h5>
                        <p>По вопросам сотрудничества и деловой переписки пишите нам на почту.</p>
                        <!-- Buttons -->
                        <a href="#" class="btn btn-link text-decoration-underline p-0 mb-0"><i class="bi bi-envelope me-1"></i> info@c-sp.kz</a>
                    </div>
                </div>
                <!-- Contact item END -->
            
                <!-- Contact item START -->
                <div class="col-xl-4 position-relative d-none d-md-block">
                    <!-- Svg decoration -->
                    <figure class="position-absolute top-0 end-0 z-index-1 mt-n4 ms-n7">
                        <svg class="fill-warning" width="77px" height="77px">
                            <path d="M76.997,41.258 L45.173,41.258 L67.676,63.760 L63.763,67.673 L41.261,45.171 L41.261,76.994 L35.728,76.994 L35.728,45.171 L13.226,67.673 L9.313,63.760 L31.816,41.258 L-0.007,41.258 L-0.007,35.725 L31.816,35.725 L9.313,13.223 L13.226,9.311 L35.728,31.813 L35.728,-0.010 L41.261,-0.010 L41.261,31.813 L63.763,9.311 L67.676,13.223 L45.174,35.725 L76.997,35.725 L76.997,41.258 Z"></path>
                        </svg>
                    </figure>
            
                    <div class="card card-body shadow text-center align-items-center h-100">
                        <!-- Icon -->
                        <div class="icon-lg bg-orange bg-opacity-10 text-orange rounded-circle mb-2"><i class="bi bi-globe2 fs-5"></i></div>
                        <!-- Title -->
                        <h5> Социальные сети </h5>
                        <p>Подписывайтесь на нас в социальных сетях, чтобы быть в курсе новостей!</p>
                        <!-- Buttons -->
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item"> <a class="btn btn-sm bg-facebook px-2 mb-0" href="#"><i class="fab fa-fw fa-facebook-f"></i></a> </li>
                            <li class="list-inline-item"> <a class="btn btn-sm bg-instagram px-2 mb-0" href="#"><i class="fab fa-fw fa-instagram"></i></a> </li>
                            <li class="list-inline-item"> <a class="btn btn-sm bg-twitter px-2 mb-0" href="#"><i class="fab fa-fw fa-twitter"></i></a> </li>
                            <li class="list-inline-item"> <a class="btn btn-sm bg-linkedin px-2 mb-0" href="#"><i class="fab fa-fw fa-linkedin-in"></i></a> </li>
                        </ul>
                    </div>
                </div>
                <!-- Contact item END -->
            
            </div>
            
        </div>
    </section>
    <!-- =======================
    Main banner START -->
    
    <!-- =======================
    Contact form and vector START -->
    <section class="pt-0 pt-lg-5">
        <div class="container">
            <div class="row g-4 g-lg-5 align-items-center">
                <!-- Vector image START -->
                <div class="col-lg-6 text-center">
                    <img class="blur-bottom" src="{% static 'images/tech/stroitel.webp' %}" alt="">
                </div>
                <style>
                    .blur-bottom {
                        position: relative;
                        display: block;
                        width: 100%;
                        height: auto;
                        -webkit-mask-image: linear-gradient(to bottom, rgba(0,0,0,1) 70%, rgba(0,0,0,0) 100%);
                        mask-image: linear-gradient(to bottom, rgba(0,0,0,1) 70%, rgba(0,0,0,0) 100%);
                    }                    
                </style>                
                <!-- Vector image END -->
    
                <!-- Contact form START -->
                <div class="col-lg-6">
                    <div class="card bg-light p-4">
                        <!-- Svg decoration -->
                        <figure class="position-absolute end-0 bottom-0 mb-n4 me-n2">
                            <svg class="fill-orange" style="fill: #032655 !important;" width="104.2px" height="95.2px">
                                <circle cx="2.6" cy="92.6" r="2.6"></circle>
                                <circle cx="2.6" cy="77.6" r="2.6"></circle>
                                <circle cx="2.6" cy="62.6" r="2.6"></circle>
                                <circle cx="2.6" cy="47.6" r="2.6"></circle>
                                <circle cx="2.6" cy="32.6" r="2.6"></circle>
                                <circle cx="2.6" cy="17.6" r="2.6"></circle>
                                <circle cx="2.6" cy="2.6" r="2.6"></circle>
                                <circle cx="22.4" cy="92.6" r="2.6"></circle>
                                <circle cx="22.4" cy="77.6" r="2.6"></circle>
                                <circle cx="22.4" cy="62.6" r="2.6"></circle>
                                <circle cx="22.4" cy="47.6" r="2.6"></circle>
                                <circle cx="22.4" cy="32.6" r="2.6"></circle>
                                <circle cx="22.4" cy="17.6" r="2.6"></circle>
                                <circle cx="22.4" cy="2.6" r="2.6"></circle>
                                <circle cx="42.2" cy="92.6" r="2.6"></circle>
                                <circle cx="42.2" cy="77.6" r="2.6"></circle>
                                <circle cx="42.2" cy="62.6" r="2.6"></circle>
                                <circle cx="42.2" cy="47.6" r="2.6"></circle>
                                <circle cx="42.2" cy="32.6" r="2.6"></circle>
                                <circle cx="42.2" cy="17.6" r="2.6"></circle>
                                <circle cx="42.2" cy="2.6" r="2.6"></circle>
                                <circle cx="62" cy="92.6" r="2.6"></circle>
                                <circle cx="62" cy="77.6" r="2.6"></circle>
                                <circle cx="62" cy="62.6" r="2.6"></circle>
                                <circle cx="62" cy="47.6" r="2.6"></circle>
                                <circle cx="62" cy="32.6" r="2.6"></circle>
                                <circle cx="62" cy="17.6" r="2.6"></circle>
                                <circle cx="62" cy="2.6" r="2.6"></circle>
                                <circle cx="81.8" cy="92.6" r="2.6"></circle>
                                <circle cx="81.8" cy="77.6" r="2.6"></circle>
                                <circle cx="81.8" cy="62.6" r="2.6"></circle>
                                <circle cx="81.8" cy="47.6" r="2.6"></circle>
                                <circle cx="81.8" cy="32.6" r="2.6"></circle>
                                <circle cx="81.8" cy="17.6" r="2.6"></circle>
                                <circle cx="81.8" cy="2.6" r="2.6"></circle>
                                <circle cx="101.7" cy="92.6" r="2.6"></circle>
                                <circle cx="101.7" cy="77.6" r="2.6"></circle>
                                <circle cx="101.7" cy="62.6" r="2.6"></circle>
                                <circle cx="101.7" cy="47.6" r="2.6"></circle>
                                <circle cx="101.7" cy="32.6" r="2.6"></circle>
                                <circle cx="101.7" cy="17.6" r="2.6"></circle>
                                <circle cx="101.7" cy="2.6" r="2.6"></circle>
                            </svg>
                        </figure>
    
                        <!-- Card header -->
                        <div class="card-header bg-light p-0 pb-3">
                            <h3 class="mb-0">Оставьте заявку</h3>
                        </div>
    
                        <!-- Card body START -->
                        <div class="card-body p-0">
                            <form class="row g-4">
                                <!-- Name -->
                                <div class="col-md-6">
                                    <label class="form-label">Ваше имя *</label>
                                    <input type="text" class="form-control">
                                </div>
                                <!-- Email -->
                                <div class="col-md-6">
                                    <label class="form-label">Email *</label>
                                    <input type="email" class="form-control">
                                </div>
                                <!-- Mobile number -->
                                <div class="col-12">
                                    <label class="form-label">Номер телефона *</label>
                                    <input type="text" class="form-control">
                                </div>
                                <!-- Message -->
                                <div class="col-12">
                                    <label class="form-label">Сообщение *</label>
                                    <textarea class="form-control" rows="3"></textarea>
                                </div>
                                <!-- Checkbox -->
                                <div class="col-12 form-check ms-2">
                                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                    <label class="form-check-label" for="exampleCheck1">
                                        Я соглашаюсь на политику конфидинциальности.
                                    </label>
                                </div>
                                <!-- Button -->
                                <div class="col-12">
                                    <button class="btn mb-0" style="background-color: #032655; color: white;" type="button">Отправить</button>
                                </div>	
                            </form>
                        </div>
                        <!-- Card body END -->
                    </div>
                </div>
                <!-- Contact form END -->
            </div>
        </div>
    </section>
    <!-- =======================
    Contact form and vector END -->
    
    <!-- =======================
    Map START -->
    <section class="pt-0 pt-lg-5">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <iframe class="w-100 h-300px grayscale rounded" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1204.4593357332221!2d76.84421869329081!3d43.257745690739426!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x388369f5be26863d%3A0x4879dcb3a84c4c56!2zMSwg0L_RgNC-0YHQv9C10LrRgiDQoNGL0YHQutGD0LvQvtCy0LAgMjAyLCDQkNC70LzQsNGC0Ys!5e0!3m2!1sru!2skz!4v1741802857487!5m2!1sru!2skz" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div>
    </section>
    <!-- =======================
    Map END -->
    
    </main>
{% endblock %}